baseURL = "https://nilsschulte.de/"
languageCode = "en-us"
title = "nilsschulte.de"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
	name = "Nils Schulte"
	email = "blog@nilsschulte.de"

pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true


[outputs]
	home = ["HTML"]
	section = ["HTML", "RSS", "Atom"]

[mediaTypes."application/atom+xml"]
	suffixes = ["xml"]

[outputFormats.RSS]
	mediaType = "application/xml"
	baseName = "rss"
[outputFormats.Atom]
	mediaType = "application/atom+xml"
	baseName = "atom"
